package teamnova.omok.glue.rule;

public enum RuleType {
    UNKNOWN,
    LOBBY,
    TURN_STARTING,
    TURN_PERSONAL_STARTING,
    TURN_WAITING,
    MOVE_VALIDATING,
    MOVE_APPLYING,
    OUTCOME_EVALUATING,
    TURN_PERSONAL_COMPLETED,
    TURN_ROUND_COMPLETED,
    POST_GAME_DECISION_WAITING,
    POST_GAME_DECISION_RESOLVING,
    SESSION_REMATCH_PREPARING,
    SESSION_TERMINATING,
    COMPLETED
}
